"""Add progress column to Project model

Revision ID: 323f33f93121
Revises: 
Create Date: 2024-04-25 20:52:32.350910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323f33f93121'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=False, server_default="0"))
        batch_op.alter_column('progress', existing_type=sa.Integer(), nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('progress')
    # ### end Alembic commands ###
